name: Makefile CI

on:
  push:
    tags:
    - '*' 

jobs:
  making:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repo
        uses: actions/checkout@v3

      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.35.x

      - name: Make and tar binary
        run: | 
          deno compile --allow-read --allow-net --allow-env --allow-run --target aarch64-apple-darwin index.ts -o pg
          shasum -a 256 pg > checksum.txt
          tar -czvf pg.tar.gz pg

      - name: Release
        uses: softprops/action-gh-release@v1
        with: 
          files: pg.tar.gz

      - name: Clone Homebrew Repository
        uses: actions/checkout@v3
        with:
          repository: aslak01/homebrew-stuff
          token: ${{ secrets.TAP_GITHUB_TOKEN }}
          ref: master
          path: ./brew-stuff

      # https://github.com/aslak01/pg/releases/download/${GITHUB_REF#refs/tags/}/pg.tar.gz

      - name: Update Homebrew Formula
        run: |
          CHSUM = cat checksum.txt
          echo "class Pg < Formula" >> pg.rb
          echo '  desc "A cli tool to search for linux distros"' >> pg.rb
          echo '  homepage "https://github.com/aslak01/pg"' >> pg.rb
          echo '  url "https://github.com/aslak01/pg/releases/download/'${GITHUB_REF#refs/tags/}'/pg.tar.gz"' >> pg.rb
          echo '  sha256 "'${{ CHSUM }}'"' >> pg.rb
          echo '  license "MIT"' >> pg.rb
          echo "" >> pg.rb
          echo "  def install" >> pg.rb
          echo '    bin.install "pg"' >> pg.rb
          echo "  end" >> pg.rb
          echo "end" >> pg.rb
          cp pg.rb ./brew-stuff/Formula/

      - name: Push formula
        run: |
          cd ./brew-stuff
          git add .
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "formula update pg ${GITHUB_REF#refs/tags/}"
          git push

