name: Makefile CI

on:
  push:
    branches: 
      - master
      # tags:
      # - '*' 

jobs:
  making:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.35.x
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Make all
        run: make

      - name: create release
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: minor

      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with: 
          name: pg
          path: pg

      - name: Upload Binary
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./
          asset_name: pg
          asset_content_type: application/octet-stream
