name: Makefile CI

on:
  push:
    tags:
    - '*' 

env: 
  VERSION: ${{ steps.extract_version.outputs.version }}
  SHA: ${{ github.sha }}

jobs:
  making:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repo
        uses: actions/checkout@v3

      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.35.x

      - name: Make binary
        run: deno compile --allow-read --allow-net --allow-env --allow-run --target aarch64-apple-darwin index.ts -o pg-"$VERSION"

      - name: Check SHA
        run: echo "$SHA" > Release.txt
        run: cat Release.txt

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: pg

      # - name: Set up Ruby
      #   uses: actions/setup-ruby@v1
      #   with:
      #     ruby-version: 3.2.x
      #
      # - name: Update Homebrew Formula
      #   run: |
      #     
